spring:
  application:
    name: spring-data-rest

---
spring:
  profiles: local, test
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:expensedata
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
